version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
    overwrite: true

hooks:
  BeforeInstall:
    - location: script/install.sh
      timeout: 500
      runas: root


  ApplicationStop:
    - location: script/stop.sh
      timeout: 300
      runas: root


  ApplicationStart:
    - location: script/start.sh
      timeout: 300
      runas: root
